name: 'Update Node'
on: #workflow_dispatch
 schedule:
   - cron: '0 */4 * * *'
jobs:
  update_node:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
             echo "currentTime=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
             echo "currentDate=$(TZ=':Asia/Shanghai' date '+%Y%m%d')" >> $GITHUB_ENV
             echo "currentMouth=$(TZ=':Asia/Shanghai' date '+%m')" >> $GITHUB_ENV
             echo "currentYear=$(TZ=':Asia/Shanghai' date '+%Y')" >> $GITHUB_ENV
      - name: Checkout    # 获取分支的代码和提交记录
        uses: actions/checkout@v2
      - name: Downlod file
        shell: bash
        run: |
             curl -f 'https://v2rayshare.githubrowcontent.com/${{env.currentYear}}/${{env.currentMouth}}/${{env.currentDate}}.yaml' -o ${{env.currentDate}}.yaml
             curl -f 'https://v2rayshare.githubrowcontent.com/${{env.currentYear}}/${{env.currentMouth}}/${{env.currentDate}}.txt' -o lastest.txt
             ls -al .
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8      
      - name: Add auto node
        run: |
              rm -rf lastest.yaml
              python auto.py ${{env.currentDate}}.yaml lastest.yaml
              rm -rf ${{env.currentDate}}.yaml
              ls -al .
      - name: Update git
        run: |
             git config --global user.email 619744299@qq.com
             git config --global user.name hsb4657
             git pull
             echo 'update ${{env.currentTime}}' > README.md
             git add .
             git commit -m'update ${{env.currentTime}}'    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
